<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<span itemprop="brand">The Artchive</span> nace como un proyecto de fin de curso, ¿la idea? Reunir en un mismo espacio, a modo de red social, a creadores de contenido que quieran compartir sus creaciones con otros.' => '<span itemprop="brand">The Artchive</span> has born as a end-course project, the idea? Gather in a space all the content creators who wants to share their creations with other people.',


    'The Artchive puede estar <span itemprop="address">en cualquier parte</span>. Y si quieres contactar con nosotros puedes hacerlo a través de <span itemprop="telephone"><a href="/site/contact">Contactar</a></span>.' => 'The Artchive can be <span itemprop="address">anywhere</span>. And if you want to contact us you can make with the form <span itemprop="telephone"><a href="/site/contact">Contact</a></span>.',


    'El personaje con el que el nuestro se relaciona puede ser anónimo (sólo figurará su nombre) o existente (propio o de otro usuario). <br />
    Si seleccionas un personaje existente que no sea de tu propiedad, su creador deberá dar el visto bueno.' => 'The character with whom ours can relate can be anonymous (only his name would appear) or existing (of your own or owned by another user). <br />
    If you select an existing character that is not your property, its creator must give the go-ahead.',


    'Eliminar tu cuenta significa la desaparición de todos tus datos, así como de tus publicaciones y personajes en caso de que así lo desees. En ningún caso se borrarán los comentarios que hiciste en otras publicaciones, pero tranquilo, tu nombre de usuario no se verá implicado.<br />
    Esta acción no podrá ser revertida, así que considéralo sólo cuando estés completamente seguro de que ya no quieres seguir en The Artchive.' => 'Delete your account means the disappearance of all your data, as well as your publications and characters in case you wish. In no case will the comments you made in other publications be deleted, but calm, your username will not be involved. <br />This action can not be reversed, so consider it only when you are completely sure that you do not want to continue in The Artchive.',

    'Esta acción no podrá ser revertida, pero podrás volver a registrarte en un futuro con el mismo nombre.' => 'This action can not be reversed, but you can re-register in the future with the same name.',

    'Puedes elegir borrar completamente tus personajes y publicaciones, o dejarlas en The Artchive.' => 'You can choose to completely delete your characters and publications, or leave them at The Artchive.',

    'Recuerda que eliminar tu cuenta significa la desaparición de todos tus datos.' => 'Remember that deleting your account means the disappearance of all your data.',
];
