<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '(personaje de' => '',
    '(tu personaje) es' => '',
    'Acción' => '',
    'Aceptar' => '',
    'Aficiones' => '',
    'Apariencia' => '',
    'Asunto' => '',
    'Bloquear' => '',
    'Borrar' => '',
    'Campo requerido.' => '',
    'Contenido' => '',
    'Creado por' => '',
    'Creador' => '',
    'Debe ser un número entero' => '',
    'Debe ser un número entero.' => '',
    'Dejar de seguir' => '',
    'Desbloquear' => '',
    'El comentario no existe.' => '',
    'El fichero no puede superar los 200kb.' => '',
    'El personaje no existe.' => '',
    'El usuario no existe.' => '',
    'Emisor' => '',
    'Esta relación ya existe.' => '',
    'Fecha' => '',
    'Fecha de creación' => '',
    'Fecha de envío' => '',
    'Fecha de nacimiento' => '',
    'Fecha de registro' => '',
    'Guardar como pdf' => '',
    'Ha creado ' => '',
    'Ha eliminado ' => '',
    'Ha modificado ' => '',
    'Ha sido aceptada' => '',
    'Ha sido respondida' => '',
    'Has recibido' => '',
    'Hechos destacables' => '',
    'Historia' => '',
    'La publicación no existe.' => '',
    'La relación no existe' => '',
    'La relación no existe.' => '',
    'Mandar MP' => '',
    'Modificar' => '',
    'No puede superar los 255 caracteres' => '',
    'No puede superar los 255 carácteres.' => '',
    'Nombre' => '',
    'Nombre de usuario' => '',
    'Notificación' => '',
    'Personaje anónimo' => '',
    'Personaje existente' => '',
    'Personalidad' => '',
    'Página Web' => '',
    'Página web' => '',
    'Receptor' => '',
    'Rechazar' => '',
    'Recibido' => '',
    'Se ha solicitado crear una relación con ' => '',
    'Se solicita confirmación de que' => '',
    'Seguidores' => '',
    'Seguir' => '',
    'Siguiendo' => '',
    'Sobre mi' => '',
    'Temática Favorita' => '',
    'Temática favorita' => '',
    'Tipo de relación' => '',
    'Tipo de usuario' => '',
    'Título' => '',
    'Ver personajes' => '',
    'Visto' => '',
    'de' => '',
    'un comentario' => '',
    '¡No puedes seleccionar a tu mismo personaje!' => '',
    '¡Sólo puedes elegir uno a la vez!' => '',
    '¡Uno de los dos campos debe estar relleno!' => '',
    '¿Seguro que desea borrar el personaje? No podrá ser recuperado.' => '',
    '¿Seguro que desea borrar la publicación? No podrá ser recuperada.' => '',
    'Última actualización' => '',
    'The requested page does not exist.' => '@@@@',
    'Usuario ID' => '@@@@',
    'La página requerida no existe.' => 'The requested page does not exist.',
    'Nombre de usuario o contraseña incorrecta.' => 'Incorrect username or password.',
];
