<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Acción' => '',
    'Apariencia' => '',
    'Asunto' => '',
    'Borrar' => '',
    'Campo requerido.' => '',
    'Contenido' => '',
    'Creado por' => '',
    'Creador' => '',
    'Debe ser un número entero' => '',
    'Debe ser un número entero.' => '',
    'El comentario no existe.' => '',
    'El personaje no existe.' => '',
    'El usuario no existe.' => '',
    'Emisor' => '',
    'Esta relación ya existe.' => '',
    'Fecha' => '',
    'Fecha de creación' => '',
    'Fecha de envío' => '',
    'Fecha de nacimiento' => '',
    'Ha eliminado ' => '',
    'Hechos destacables' => '',
    'Historia' => '',
    'La publicación no existe.' => '',
    'La relación no existe.' => '',
    'Modificar' => '',
    'No puede superar los 255 carácteres.' => '',
    'Nombre' => '',
    'Notificación' => '',
    'Personaje anónimo' => '',
    'Personaje existente' => '',
    'Personalidad' => '',
    'Receptor' => '',
    'Recibido' => '',
    'Se ha solicitado crear una relación con ' => '',
    'Tipo de relación' => '',
    'Título' => '',
    'Visto' => '',
    'un comentario' => '',
    '¡No puedes seleccionar a tu mismo personaje!' => '',
    '¡Sólo puedes elegir uno a la vez!' => '',
    '¡Uno de los dos campos debe estar relleno!' => '',
    '¿Seguro que desea borrar el personaje? No podrá ser recuperado.' => '',
    '¿Seguro que desea borrar la publicación? No podrá ser recuperada.' => '',
    'Última actualización' => '',
    'Usuario ID' => '@@@@',
    'Nombre de usuario o contraseña incorrecta.' => 'Incorrect username or password.',
];
