<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Password' => 'Contraseña',
    'Recordarme' => 'Remember me',
    '(personaje de' => '(character of',
    '(tu personaje) es' => '(your character) is',
    'Acción' => 'Action',
    'Aceptar' => 'Accept',
    'Aficiones' => 'Hobbies',
    'Apariencia' => 'Physical appearance',
    'Asunto' => 'Subject',
    'Bloquear' => 'Block',
    'Borrar' => 'Delete',
    'Buscar' => 'Search',
    'Campo requerido.' => 'Required field.',
    'Contenido' => 'Content',
    'Creado por' => 'Created by',
    'Creador' => 'Creator',
    'Debe ser un número entero' => 'It must be a whole number',
    'Debe ser un número entero.' => 'It must be a whole number.',
    'Dejar de seguir' => 'Unfollow',
    'Desbloquear' => 'Unblock',
    'El comentario no existe.' => 'The comment doesn\'t exist',
    'El fichero no puede superar los 200kb.' => 'Limit is 200kb.',
    'El personaje no existe.' => 'Character doesn\'t exist',
    'El usuario no existe.' => 'User doesn\'t exist',
    'Emisor' => 'Sender',
    'Esta relación ya existe.' => 'This relationship already exists.',
    'Fecha' => 'Date',
    'Fecha de creación' => 'Creation date',
    'Fecha de envío' => 'Send date',
    'Fecha de nacimiento' => 'Birthdate',
    'Fecha de registro' => 'Registration date',
    'Guardar como pdf' => 'Save as pdf',
    'Ha creado ' => 'Has created ',
    'Ha eliminado ' => 'Has deleted ',
    'Ha modificado ' => 'Has modified ',
    'Ha sido aceptada' => 'Has been accepted',
    'Ha sido respondida' => 'Has ben answered',
    'Has recibido' => 'You have recieved',
    'Hechos destacables' => 'Highlights',
    'Historia' => 'Story',
    'La publicación no existe.' => 'This publication doesn\'t exist.',
    'La página requerida no existe.' => 'The requested page does not exist.',
    'La relación no existe' => 'This relationship doesn\'t exist.',
    'La relación no existe.' => 'This relationship doesn\'t exist.',
    'Mandar MP' => 'Send PM',
    'Modificar' => 'Modify',
    'No puede superar los 255 caracteres' => 'It can not exceed 255 characters.',
    'No puede superar los 255 carácteres.' => 'It can not exceed 255 characters.',
    'Nombre' => 'Name',
    'Nombre de usuario' => 'Username',
    'Nombre de usuario o contraseña incorrecta.' => 'Incorrect username or password.',
    'Notificación' => 'Alert',
    'Personaje anónimo' => 'Anonymous character',
    'Personaje existente' => 'Existing character',
    'Personalidad' => 'Personality',
    'Página Web' => 'Web page',
    'Página web' => 'Web page',
    'Receptor' => 'Receiver',
    'Rechazar' => 'Reject',
    'Recibido' => 'Received',
    'Se ha solicitado crear una relación con ' => 'You have been requested to create a relationship with ',
    'Se solicita confirmación de que' => 'Confirmation is requested that',
    'Seguidores' => 'Followers',
    'Seguir' => 'Follow',
    'Siguiendo' => 'Following',
    'Sobre mi' => 'About me',
    'Temática Favorita' => 'Favorite theme',
    'Temática favorita' => 'Favorite theme',
    'Tipo de relación' => 'Type of relationship',
    'Tipo de usuario' => 'Type of user',
    'Título' => 'Title',
    'Ver personajes' => 'Characters',
    'Visto' => 'Seen',
    'de' => 'of',
    'un comentario' => 'a comment',
    '¡No puedes seleccionar a tu mismo personaje!' => 'You can\'t select your own character!',
    '¡Sólo puedes elegir uno a la vez!' => 'You can only choose one at a time!',
    '¡Uno de los dos campos debe estar relleno!' => 'One of the two fields must be filled!',
    '¿Seguro que desea borrar el personaje? No podrá ser recuperado.' => 'Are you sure you want to delete your character? It can not be recovered.',
    '¿Seguro que desea borrar la publicación? No podrá ser recuperada.' => 'Are you sure you want to delete your publication? It can not be recovered.',
    'Última actualización' => 'Last update',
];
