<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Conectarte' => 'Login',
    'Enviar' => 'Send',
    'Este error ocurrió mientras el servidor procesaba tu respuesta.' => 'The above error occurred while the Web server was processing your request.',
    'Guardar' => 'Save',
    'Hola' => 'Hello',
    'Por favor contacta con nosotros si piensas que es un error del servidor. Gracias.' => 'Please contact us if you think this is a server error. Thank you.',
    'Por favor, elige una nueva contraseña:' => 'Please choose a new password:',
    'Por favor, introduce tu email. Se enviará un link para resetear la contraseña.' => 'Please introduce your email. A link will be send to reset your password.',
    'Por favor, rellena los siguientes apartados para conectarte:' => 'Please fill out the following fields to login:',
    'Por favor, rellena los siguientes apartados para registrarte:' => 'Please fill out the following fields to signup:',
    'Registrarte' => 'Signup',
    'Si has olvidado tu contraseña puedes' => 'If you forgot your password you can',
    'resetearla' => 'reset it',
];
